name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Set your region

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Infrastructure
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan

    - name: Extract Instance IPs
      id: get_ips
      run: |
            INSTANCE_IPS=$(terraform output -json linux_server_ips | jq -r '.[]')
            echo "INSTANCE_IPS=$INSTANCE_IPS" >> $GITHUB_ENV

    - name: Run Tests on Server
      run: |
            echo "INSTANCE_IPS"
            chmod 600 ais2025.ppk
            ssh -o StrictHostKeyChecking=no -i ais2025.ppk ubuntu@$INSTANCE_IPS 'bash -s' < test-server.sh


    # - name: Run Tests on All Servers
    #  run: |
    #      chmod +x test-server.sh
    #     for IP in $INSTANCE_IPS; do
    #       ./test-server.sh $IP
    #     done
